import { CharacterSkin } from './types';

export const CHARACTER_SKINS: CharacterSkin[] = [
  {
    id: 'boneca_sd_pixel_v2',
    name: 'ボネカ',
    category: 'default',
    unlockMethod: 'default',
    rarity: 'common',
    isDefault: true,
    assetKey: 'boneca_sd_pixel_v2',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: false,
    evolutionStageIndex: 0,
  },
  {
    id: 'luliloli_sd_pixel',
    name: 'ルリロリ',
    category: 'default',
    unlockMethod: 'default',
    rarity: 'common',
    isDefault: false,
    assetKey: 'luliloli_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: false,
    evolutionStageIndex: 0,
  },
  {
    id: 'boneca_sd_pixel_v2_evo2',
    name: 'ボネカ（進化）',
    category: 'default',
    unlockMethod: 'evolution',
    rarity: 'rare',
    isDefault: false,
    assetKey: 'boneca_sd_pixel_v2',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: false,
    evolutionStageIndex: 1,
  },
  {
    id: 'luliloli_sd_pixel_evo2',
    name: 'ルリロリ（進化）',
    category: 'default',
    unlockMethod: 'evolution',
    rarity: 'rare',
    isDefault: false,
    assetKey: 'luliloli_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: false,
    evolutionStageIndex: 1,
  },
  {
    id: 'capuchino_sd_pixel_v4',
    name: 'カプチーノ',
    category: 'study',
    unlockMethod: 'shop',
    rarity: 'common',
    isDefault: false,
    shopCost: 100,
    minLevel: 1,
    assetKey: 'capuchino_sd_pixel_v4',
    isSelectableBuddy: true,
    isShopVisible: true,
    isGachaVisible: false,
  },
  {
    id: 'frigo_sd_pixel',
    name: 'フリゴ',
    category: 'study',
    unlockMethod: 'shop',
    rarity: 'common',
    isDefault: false,
    shopCost: 100,
    minLevel: 1,
    assetKey: 'frigo_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: true,
    isGachaVisible: false,
  },
  {
    id: 'lirili_sd_pixel',
    name: 'リリリ',
    category: 'study',
    unlockMethod: 'shop',
    rarity: 'rare',
    isDefault: false,
    shopCost: 150,
    minLevel: 2,
    assetKey: 'lirili_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: true,
    isGachaVisible: false,
  },
  {
    id: 'cocochini_sd_pixel_fix',
    name: 'ココチーニ',
    category: 'study',
    unlockMethod: 'gacha',
    rarity: 'common',
    isDefault: false,
    gachaWeight: 4,
    minLevel: 2,
    assetKey: 'cocochini_sd_pixel_fix',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: true,
  },
  {
    id: 'piccione_sd_pixel_fix',
    name: 'ピッチョーネ',
    category: 'study',
    unlockMethod: 'gacha',
    rarity: 'rare',
    isDefault: false,
    gachaWeight: 3,
    minLevel: 3,
    assetKey: 'piccione_sd_pixel_fix',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: true,
  },
  {
    id: 'udindindindun_sd_pixel',
    name: 'ウディンディンディンドゥン',
    category: 'study',
    unlockMethod: 'gacha',
    rarity: 'epic',
    isDefault: false,
    gachaWeight: 2,
    minLevel: 4,
    assetKey: 'udindindindun_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: true,
  },
  {
    id: 'barerina_sd_pixel',
    name: 'バレリーナ',
    category: 'exercise',
    unlockMethod: 'shop',
    rarity: 'common',
    isDefault: false,
    shopCost: 100,
    minLevel: 1,
    assetKey: 'barerina_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: true,
    isGachaVisible: false,
  },
  {
    id: 'bonbal_sd_pixel',
    name: 'ボンバル',
    category: 'exercise',
    unlockMethod: 'shop',
    rarity: 'common',
    isDefault: false,
    shopCost: 100,
    minLevel: 1,
    assetKey: 'bonbal_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: true,
    isGachaVisible: false,
  },
  {
    id: 'tatata_sd_pixel',
    name: 'タタタ',
    category: 'exercise',
    unlockMethod: 'shop',
    rarity: 'rare',
    isDefault: false,
    shopCost: 150,
    minLevel: 2,
    assetKey: 'tatata_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: true,
    isGachaVisible: false,
  },
  {
    id: 'chinpanzini_sd_pixel',
    name: 'チンパンジーニ',
    category: 'exercise',
    unlockMethod: 'gacha',
    rarity: 'rare',
    isDefault: false,
    gachaWeight: 3,
    minLevel: 2,
    assetKey: 'chinpanzini_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: true,
  },
  {
    id: 'toruca_sd_pixel',
    name: 'トルカ',
    category: 'exercise',
    unlockMethod: 'gacha',
    rarity: 'rare',
    isDefault: false,
    gachaWeight: 3,
    minLevel: 3,
    assetKey: 'toruca_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: true,
  },
  {
    id: 'tuntun_sd_pixel_v3',
    name: 'トゥントゥン',
    category: 'exercise',
    unlockMethod: 'gacha',
    rarity: 'rare',
    isDefault: false,
    gachaWeight: 3,
    minLevel: 3,
    assetKey: 'tuntun_sd_pixel_v3',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: true,
  },
  {
    id: 'brrbrrpatapim_sd_pixel',
    name: 'ブリブリパタピム',
    category: 'exercise',
    unlockMethod: 'gacha',
    rarity: 'epic',
    isDefault: false,
    gachaWeight: 1,
    minLevel: 4,
    assetKey: 'brrbrrpatapim_sd_pixel',
    isSelectableBuddy: true,
    isShopVisible: false,
    isGachaVisible: true,
  },
];

export function resolveAssetKey(formId: string): string {
  return getSkinById(formId)?.assetKey ?? formId;
}

export function isSkinSelectableBuddy(skin: CharacterSkin): boolean {
  if (skin.isSelectableBuddy !== undefined) return skin.isSelectableBuddy;
  return true;
}

export function isSkinShopVisible(skin: CharacterSkin): boolean {
  if (skin.isShopVisible !== undefined) return skin.isShopVisible;
  return skin.unlockMethod === 'shop';
}

export function isSkinGachaVisible(skin: CharacterSkin): boolean {
  if (skin.isGachaVisible !== undefined) return skin.isGachaVisible;
  return skin.unlockMethod === 'gacha';
}

export function getAllSkins(includeExtra: boolean): CharacterSkin[] {
  if (includeExtra) return CHARACTER_SKINS;
  return CHARACTER_SKINS.filter(
    (skin) => skin.unlockMethod === 'default' || skin.unlockMethod === 'evolution'
  );
}

export function getSkinById(id: string): CharacterSkin | undefined {
  return CHARACTER_SKINS.find((s) => s.id === id);
}
